- source/DWGUGens/dwglib/DWG.hpp
- source/DWGUGens/sc/HelpSource/Classes/DWGPluckedStiff.schelp
- source/OteyPianoUGens/DWG.cpp
- source/OteyPianoUGens/DWG.hpp
- source/OteyPianoUGens/OteyPiano.cpp
add help file for DWGPluckedStiff
and
OteyPianoUGens add kill_denormals
> two pull requests

- source/DWGUGens/DWGBowed.cpp
- source/DWGUGens/dwglib/DWG.hpp
dwgugens: disallow print statements 	
dwgbowed: allow DWGSoundBoard mix to be changed
> Dwgchanges

- source/StkInst/CMakeLists.txt
plus a minor change for not compiling one not needed file
> StkInst: cmake warning for submodule update

- CMakeLists.txt
- cmake_modules/FindSTK.cmake
- source/CMakeLists.txt
- source/StkInst/CMakeLists.txt
- source/StkUGens/StkAll.cpp
Based on patch by @hzulla:
https://github.com/deb-pkg-sonic-pi/pkg-supercollider-sc3-plugins/blob/master/debian/patches/02-debian-libstk.patch
> Add cmake build option SYSTEM_STK

- source/DWGUGens/dwglib/DWG.hpp
> dwglib: std::min -> sc_min

- source/BlackrainUGens/sc/HelpSource/Classes/AmplitudeMod.schelp
> deprecate AmplitudeMod in help file

- source/JoshUGens/sc/HelpSource/Classes/OverlapTexture.schelp
- source/JoshUGens/sc/HelpSource/Classes/WarpOverlap.schelp
Converted old html help for OverlapTexture and WarpOverlap to SCDoc
format.
> JoshUGens: Help: convert to SCDoc

- source/JoshUGens/sc/HelpSource/Classes/AtsAmp.schelp
- source/JoshUGens/sc/HelpSource/Classes/AtsBand.schelp
- source/JoshUGens/sc/HelpSource/Classes/AtsFile.schelp
- source/JoshUGens/sc/HelpSource/Classes/AtsFreq.schelp
- source/JoshUGens/sc/HelpSource/Classes/AtsNoiSynth.schelp
- source/JoshUGens/sc/HelpSource/Classes/AtsParInfo.schelp
- source/JoshUGens/sc/HelpSource/Classes/AtsSynth.schelp
- source/JoshUGens/sc/HelpSource/Classes/BFDecode1.schelp
- source/JoshUGens/sc/HelpSource/Classes/BFEncode1.schelp
- source/JoshUGens/sc/HelpSource/Classes/BFEncode2.schelp
- source/JoshUGens/sc/HelpSource/Classes/BFEncodeSter.schelp
- source/JoshUGens/sc/HelpSource/Classes/BFManipulate.schelp
- source/JoshUGens/sc/HelpSource/Classes/Balance.schelp
- source/JoshUGens/sc/HelpSource/Classes/BufGrain.schelp
- source/JoshUGens/sc/HelpSource/Classes/BufGrainB.schelp
- source/JoshUGens/sc/HelpSource/Classes/BufGrainI.schelp
- source/JoshUGens/sc/HelpSource/Classes/OverlapTexture.schelp
- source/JoshUGens/sc/HelpSource/Classes/WarpOverlap.schelp
- source/JoshUGens/sc/HelpSource/Classes/WarpZ.schelp
Converted a new batch of old help files to the SCDoc format.
> JoshUgens: help: update to SCDoc

- source/JoshUGens/sc/classes/TheBFMixer.sc
Changed from using `SC*` gui classes to new classes without `SC`-prefix in `TheBFMixer.sc`
> JoshUGens: Class: changed old SC gui classes

- CMakeLists.txt
We should at least be building plugins for supernova when we're building it in the SC repo
> Build plugins for supernova if we built it

- source/DWGUGens/dwglib/DWG.hpp
> DWGUGens: fix float/double confusion for GCC 6 compatibility (take 2)

- source/SLUGens/SLUGens.cpp
For background: https://github.com/supercollider/supercollider/issues/2333. Sorry if it's kind of weird to only fix this one when the rest of the SLUGens are also in need of attention. I use EnvFollow a lot.
> EnvFollow: initialize outputs

- source/LadspaUGen/LadspaUGen.cpp
> Remove initialization output from LADSPA UGen

- source/ATK/sc/Classes/ATK.sc
- source/ATK/sc/Classes/ATKMatrix.sc
> class library: fix inline warnings

- source/DWGUGens/sc/HelpSource/Classes/DWGPluckedStiff.schelp
Convert encoding of DWGPluckedStiff help file from iso-8859-1 to UTF-8.
> DWGUGen: Convert iso-8859-1 character to UTF-8 in help

- source/SkUGens/sc/HelpSource/Classes/FM7.schelp
Fix for issue - https://github.com/supercollider/sc3-plugins/issues/151
> Update description for algo argument in arAlgo method

- source/StkInst/CMakeLists.txt
Fixed https://github.com/supercollider/sc3-plugins/issues/159
> Fixed missing dependency of StkInst_supernova.so on libstk.so

- CMakeLists.txt
- DEVELOPING.md
- README.md
- README_MACOS.txt.in
- README_WINDOWS.txt.in
- Add info about packaging/release process in a new DEVELOPING.md
- Add a configurable README for MacOS which can be included in releases
- As a result, Fixes #166
- Make a slight tweak to the readme that was unnecessarily Linuxy
> Updates to docs and packaging

- source/JoshUGens/JoshPVUGens.cpp
> JoshPVUGens: PV_Freeze, refactor _next() to init properly and avoid hang

- source/CMakeLists.txt
* CMAKE_SYSTEM_NAME match
* Use of ${CMAKE_DL_LIBS}
> Compatibility with BSD systems

- CMakeLists.txt
> cmake: consider both Clang and AppleClang as clang

- source/NHUGens/nh_hall.hpp
reduces some of the odd stereo wobble on transients
> NHHall: Improve early reflections

- source/NHUGens/nh_hall.hpp
was causing errors in appveyor. oops...
> NHUGens: Fix incorrect return type in NHHall

- source/CMakeLists.txt
- source/StkInst/CMakeLists.txt
these are in external_libraries/boost now
> cmake: remove refs to missing dirs

- source/DWGUGens/sc/HelpSource/Classes/DWGPluckedStiff.schelp
\#230
Update DWGPluckedStiff.schelp
fixed missing release argument. as reported on sc-users https://www.listarc.bham.ac.uk/lists/sc-users/msg62915.html
> 3.10 - cherry-pick #230

- source/BlackrainUGens/BlackrainUGens.cpp
- source/JoshUGens/JoshGrainUGens.cpp
- source/NCAnalysisUGens/MedianSeparation.cpp
- source/OteyPianoUGens/hammer.cpp
- source/OteyPianoUGens/hammer.h
- source/PitchDetection/Qitch.cpp
- source/RFWUGens/RFWUGens.cpp
> Cherrypick #244 into 3.10

- _data/releases.yml
after this i'll tag the 3.11.1 release
> Update releases.yml for 3.11.1

- source/SCMIRUGens/OnsetStatistics.cpp
note, files in DEINDUGens use master/slave but those are copy-pasted files from faust, so i haven't updated those. should change upstream
part of https://github.com/supercollider/supercollider/issues/5251
> change master->main in comment

- README.md
> docs: if you don't want SUPERNOVA you actually have to explicitly disable it

- .github/workflows/CI.yml
I forgot about this when making the first PR - otherwise we might get compatibility issues with older systems...
> gha: specify xcode and deployment target for macOS

- README.md
- source/CMakeLists.txt
https://github.com/supercollider/sc3-plugins/issues/309
Allow option to add `LIB_SUFFIX` to cmake.
> Add option for LIB_SUFFIX

- source/CMakeLists.txt
See https://github.com/supercollider/supercollider/pull/5728 for description of analogous fix in SuperCollider
> CMakeLists: fix LIB_SUFFIX

- source/DEINDUGens/sc/HelpSource/Classes/GreyholeRaw.schelp
This one has been bothering me for years.
I have no idea what the difference is in line 53, they look exactly the same to me.
> DEINDUGens HelpSource: Remove unnecessary text

- .github/workflows/CI.yml
This should allow us to manually trigger Ci for old PRs... maybe?
@capital-G what do you think?
> Add workflow_dispatch trigger to CI workflow
