supercollider/sc3-plugins

- source/JoshUGens/sc/classes/LPCFile.sc
This fixes two issues in LPCFile:loadToBuffer:
1. `this.loadToSignal` was called twice, wasting CPU time.
2. LPCFile's `init` method reserves a buffer number, but then `loadToBuffer` uses `Buffer.loadCollection` -- which ignores the previously reserved bufnum and allocates a new one. The first one is never released back to theServer.bufferAllocator, so... the class leaks buffer numbers.
Now, LPCFile will keep using the same buffer number that was allocated at first.
> LPCFile.sc: loadToBuffer: Use existing bufnum, don't loadToSignal twice

- source/BhobUGens/BhobNoise.cpp
The plugin description, various helpfiles and a class refer to Gendy5, but here we find Gendy0 nex to Gendy4. Is exchanging Gendy0 by Gendy5 a proper fix? (the result sounds as intended)
> Exchange Gendy0 references by Gendy5

- source/ATK/sc/Classes/ATK.sc
Currently FoaEncode/FoaDecode only accept encoders and decoders that are strict members of four ATK classes. I ran into this problem when trying to extend them, so this change allows them to accept subclasses.
> ATK: Generalize FoaEncode and FoaDecode behavior

- source/ATK/AtkUGens.cpp
branches and memory are MUCH slower than doing the actual computation.
this patch speeds roughly doubles the performance of atk panners
> atk: avoid branches in inner loop and memory hazards

- source/StkInst/CMakeLists.txt
Stefan Nussbaumer says it also need submodule init
> StkInst: cmake warning to use submodule update and submodule init

- source/CMakeLists.txt
This fixes https://github.com/deb-pkg-sonic-pi/pkg-supercollider-sc3-plugins/issues/1
Two UGens were missing information for their shared libraries on Linux.
> Linux linking fixed

- source/BBCut2UGens/DrumTrack.cpp
- source/BBCut2UGens/sc/DrumTrack.sc
- source/BBCut2UGens/sc/HelpSource/Classes/DrumTrack.schelp
I'm the current maintainer of Nick Collins' BBCut2, and I am trying to get it packaged as a quark. It contains around 50 classes for sclang and three ugens: AnalyseEvents2, AutoTrack, and DrumTrack. Since quarks are client-only extensions, I need to get these out of the BBCut2 repository.
AnalyseEvents2 is in sc3-plugins and AutoTrack is in core (now known as BeatTrack), but for some reason DrumTrack was left behind. So DrumTrack needs a new home, and sc3-plugins seems like a reasonable place to put it.
Sorry for submitting such a large PR...
> Add DrumTrack from BBCut2

- source/AntiAliasingOscillators/AntiAliasingOscillators.cpp
- source/AntiAliasingOscillators/sc/Classes/AntiAliasingOscillators.sc
Fixes #82 with smarter phase tracking. A few extra divides and multiplies per control period, but shouldn't be huge.
Sorry about the absurd diff, my editor removed a bunch of trailing whitespace. I didn't feel like turning it off because we might as well get rid of it.
> BlitB3 -- fix oscillator freezing

- source/DEINDUGens/faust_src/Greyhole.sc
- source/DEINDUGens/faust_src/JPverb.sc
Fixes #43. It's useful in documentation work to point SC directly to the source folder like in these instructions: http://supercollider.github.io/contributing/ideconfig-contrib
> remove duplicate classes in DEINDUGens

- source/JoshUGens/sc/HelpSource/Classes/PV_PlayBuf.schelp
- source/JoshUGens/sc/HelpSource/Classes/PV_RecordBuf.schelp
This breaks my entire help system, (which seems like also an important bug in the SCIDE)
> Trailing commas in these two help files.

- source/MCLDUGens/sc/MCLDChaosUGens.sc
ChuaL is not installed and in fact does not exist in the source.
> MCLDUGens: remove class for nonexistent UGen "ChuaL"

- source/BerlachUGens/BerlachUGens.cpp
- source/BerlachUGens/Oversamp.h
Fix #9. Turns out it's not so bad.
> BerlachUGens: get oversampling ugens working for blocksize > 64

- source/BhobUGens/BhobGrain.cpp
- source/BhobUGens/sc/HelpSource/Classes/TGrains2.schelp
- source/BhobUGens/sc/HelpSource/Classes/TGrains3.schelp
- source/BhobUGens/sc/classes/bhobGens.sc
fix #81. panning behavior was standardized in core at https://github.com/supercollider/supercollider/pull/2136
> BhobUGens: use standard panning behavior for TGrains2, TGrains3

- source/RFWUGens/RFWUGens.cpp
This is debatable: but this commit suggests that the delayfactor can be:
1. negative (you may want to emphasize only odd harmonics at an octave
lower)
2. equal or very close to one (you may want to have an infinite decay
time for a while, or with very short delaytimes, you may easily need a
factor more than the current 0.9)
This is an API change.
> plugins: SwitchDelay should not limit delayfactor

- README.md
See https://github.com/supercollider/supercollider/issues/3250
- Remove `cwd/sc3-plugins$`-style text in shell commands (confuses some users)
- Add a troubleshooting note about missing files during build (common mistake)
- Rearrange some text to improve flow
- Fix minor typos
@unculcated, what do you think?
> Make README clearer

- README.md
Fixes #176.
- merge "Release downloads" and "binary install"
- rename section "Installation"
- add info about how to evaluate code in SC
- add instructions about how to get to extensions dir and that you might need to create the folder
@yaxu I didn't change the text of the "GitHub release page" link. I'm not sure why that is confusing, and it also doesn't make grammatical sense to change it to "download latest version". If you can explain that I'd appreciate it.
> readme: make installation instructions friendlier

- CMakeLists.txt
This ensures that SC issue https://github.com/supercollider/supercollider/issues/3243 won't happen again. Also makes the error messages for missing submodules clearer.
> cmake: Check that users cloned sc's submodules when necessary

- .gitignore
This matches https://github.com/supercollider/supercollider/blob/develop/.gitignore and helps when, like me, you are trying to manage several build folders at once.
> gitignore build* instead of build

- source/VBAPUGens/VBAP.cpp
this fixes #122 and replaces #123. i'm kicking myself because i delayed on this an entire year and only just now realized how simple the bug was.
the problem was a failure to increment the channel gains by the slopes in the nova-simd version of the code.
```
~array = VBAPSpeakerArray(2, [-30, 30, 0, -110, 110]);
~buf = ~array.loadToBuffer;
{ VBAP.ar(5, DC.ar(1), ~buf.bufnum, Line.kr(0, 360, 0.05), 1.0, 0.0) }.plot(0.05);
```
before:
after:
> VBAP: Fix stairstepping during modulation

- source/RFWUGens/sc/HelpSource/Classes/SwitchDelay.schelp
It appears that the Theory and Techniques of Electronic Music PDF is no longer at this URL. However, an HTML version of the book exists so I found the appropriate link to the Switch-and-ramp technique.
> Update switch-and-ramp reference link

- .appveyor.yml
This PR adds Appveyor support for sc3-plugins so that we can have full CI coverage
The plugins are built on Windows with VS 2017 in both 32-bit and 64-bit forms.
No artifacts or uploaded have been implemented yet; this is purely to ensure CI stability. That can be added later.
> Add basic .appveyor.yml

- .gitmodules
The git protocol is unencrypted and susceptable to MITM attacks.
Simple change to use HTTPS instead of git as a protocol for the submodule. This way it's also the same for both submodules :)
> Use HTTPS for nova-simd submodule

- .gitignore
- package/create_package.sh
This is an attempt to fix #184 by creating a script, that can be called from anywhere.
It will use `/tmp` to create assets (in the form of `sc3-plugins-Version-x.x.x.tar.gz`) and then place the finished tarball beneath `package/`.
There is one pitfall: It uses `readlink -f` (see [get_absolute_path()](https://github.com/supercollider/sc3-plugins/compare/master...dvzrv:package?expand=1#diff-07e7b66d35e7dabd5131935313a81d3aR8)), which doesn't seem to be around under macOS by default, but can be installed with the coreutils package using homebrew or macports.
If you know of a valid alternative, let me know. As a workaround the script currently moves the tarball to $HOME on macOS and the package folder on Linux.
IMHO this is a much cleaner solution, than doing this in a potential working copy …
> Create assets with a script

- .gitignore
- package/create_package.sh
this PR merges #186 into 3.10 and also makes some naming tweaks for consistency with the package script in core.
> Tweak names produced by package script, merge #186 into 3.10

- source/CMakeLists.txt
- source/QuantityUGens/QuantityUGens.cpp
- source/QuantityUGens/sc/HelpSource/Classes/MovingAverage.schelp
- source/QuantityUGens/sc/HelpSource/Classes/MovingSum.schelp
- source/QuantityUGens/sc/MovingSum.sc
- source/QuantityUGens/sc/Tests/TestMovingSum.sc
Add QuantityUGens, intended for analyzing signal/soundfield quantities. Currently just adds
MovingSum, which is a variation of RunningSum that includes a variable window size. Extended to time averaging by MovingAverage class and convenience methods *power and *rms. Help docs and unit test included.
> Add QuantityUGens, MovingSum and MovingAverage

- source/QuantityUGens/QuantityUGens.cpp
This fixes #216.
**QuantityUGens.cpp** made use of `printf` which caused build issues. This PR changes `printf` to `Print`.
> [QuantityUGens] make use of Print

- .appveyor.yml
Example: https://github.com/supercollider/sc3-plugins/releases/tag/untagged-32e5ea1b607a870972fb
- package build artifacts
- upload to Github releases on tag
- use clever powershell hax to get the name right (tag Version-3.10.0 will be stripped to "3.10.0") in artifact
> appveyor: add artifacts and github deployment

- .travis.yml
This enables linux builds on travis and fixes #218:
- avoid installing unnecessary packages
- use travis default packages (`gcc`, `cmake`, `build-essentials`, ..)
- osx defaults to `Xcode-9.4.1`
> [travis] add build for linux

- .travis.yml
3.10.1 of this repo can be released immediately after this merge (cc @snappizz )
> build supernova plugins

- CMakeLists.txt
- cmake_modules/FindSuperCollider3.cmake
Fixes #185
so default builds won't fail if SC sources are not around during build time
> CMake: Fix wrong check for SUPERNOVA

- source/BlackrainUGens/BlackrainUGens.cpp
- source/JoshUGens/JoshGrainUGens.cpp
- source/NCAnalysisUGens/MedianSeparation.cpp
- source/OteyPianoUGens/hammer.cpp
- source/OteyPianoUGens/hammer.h
- source/PitchDetection/Qitch.cpp
- source/RFWUGens/RFWUGens.cpp
Fix #180
- undefine redefined macros
-    undesired promotion to double
-    fix unsequenced modification of value
-    mark destructor virtual - avoids memory leak when deleting hammer object
-    remove tautological compare - also fix bug - potential read from unallocated buffer
-    remove tautological compare
> Eliminate some clang warnings

- source/DEINDUGens/sc/HelpSource/Classes/JPverb.schelp
minor closing `::` preventing doc from rendering
> typo fix in JPVerb doc

- source/NHUGens/NHHall.cpp
This change fixes this compilation failure:
source/NHUGens/NHHall.cpp: In constructor 'NHHall::NHHall()':
source/NHUGens/NHHall.cpp:56:13: error: 'printf' was not declared in this scope
56 |             printf("Could not allocate real-time memory for NHHall\n");
|             ^~~~~~
source/NHUGens/NHHall.cpp:30:1: note: 'printf' is defined in header '<cstdio>'; did you forget to '#include <cstdio>'?
29 | #include "SC_PlugIn.hpp"
+++ |+#include <cstdio>
30 |
In file included from source/NHUGens/NHHall.cpp:28:
> Add missing cstdio import required for printf

- source/AYUGens/sc/HelpSource/Classes/AY.schelp
This PR expands documentation of the AY UGen on the following topics:
- The behavior of the three tone oscillators and how they interact to produce more complex waves than mere pulses.
- The deliberate use of DC offset (and a recommendation to use LeakDC on it).
- Details of the behavior of the `control` input (which is not intuitive... or, it might be intuitive if one already understands the oscillators' behavior).
Chip emulation works on very different principles from typical full-resolution synthesis. Explaining the principles really makes a big difference.
> Help: AY: Explain three oscillators' behavior wrt 'control' input

- DEVELOPING.md
The plugins have successfully been compiled using VS 2019 (community edition) so
the compatible VS versions have been updated. It also required a change to one
of the cmake variable names.
> Update docs - fix cmake variable reference, VS versions

- CMakeLists.txt
- README.md
- source/CMakeLists.txt
> Make LadspaUGen optional

- README.md
and an extra 'cd sc3-plugins' to make sure users are in the right directory to begin with.
the sudo is needed to avoid the following error...
```
Install the project...
-- Install configuration: ""
-- Installing: /usr/local/share/SuperCollider/Extensions/SC3plugins/local
CMake Error at source/cmake_install.cmake:41 (file):
file INSTALL cannot make directory
"/usr/local/share/SuperCollider/Extensions/SC3plugins/local": No such file
or directory
Call Stack (most recent call first):
cmake_install.cmake:42 (include)
make: *** [Makefile:74: install
```
> added a note about using sudo under linux

- source/SkUGens/sc/FM7.sc
This removes a .postln from the *arAlgo method that must have been leftover from some debugging
> Remove postln from arAlgo

- source/TagSystemUGens/sc/SymbolicMachines.sc
Posting the rules gets particularly problematic when they are very large. You can switch it back on by setting `Dfsm.verbose = true`.
> Dfsm shouldn't always post

- .github/workflows/jekyll.yml
I've created a github action that runs `bundle install` for PRs and thus should give us heads up in case PRs updating jekyll dependencies break the website.
You can see it [running successfully on my fork](https://github.com/dyfer/sc3-plugins/actions/runs/1292536285), as well as [expectedly failing](https://github.com/dyfer/sc3-plugins/actions/runs/1292543572) when I manually specified an invalid version of one package in `Gemfile.lock`. For these runs I've temporarily made the action to run on all pushes; however here it is set to run on PRs only.
This PR does _not_ provide a way to preview changes made to the website.
> Add Github action for testing website builds

- .github/workflows/CI.yml
I was working on adding ccache caching to our build system and made a number of changes/improvements along the way:
- Linux ~~and macOS~~ builds use ccache now
- ~~macOS generator was swtiched to "Unix Makefiles" since the "XCode" generator needs extra commands in CMakeLists to use ccache, see [CMakeLists in SC](https://github.com/supercollider/supercollider/blob/develop/CMakeLists.txt#L42-L66)~~
- ~~**is it OK to switch to Makefiles generator? Or should we stick to XCode generator and not care about cache for now?**~~
- After the dev meeting on Dec 4, 2021 we've decided to go back to XCode and not use ccache on macOS
- I've simplified the yaml file by moving platform-dependent cmake switches directly to the matrix entries to avoid extra logic to handle various configurations
- I've made …
> GitHub actions: ccache and other improvements

- .github/workflows/CI.yml
As we are getting ready to offer macOS binaries for both x86_64 and arm64 platforms, I tried enabling universal macOS builds for sc3-plugins as well.
I tested this briefly by booting scsynth and running an example from `Tartini`'s helpfile, and - after un-quarantining - the plugins worked on both arm64 machine with macOS 12 as well as x86_64 machine with macOS 10.10... full compatibility range.
I also updated Xcode version to match the main SC release and made some minor cosmetic updates to the CI.
> create universal macOS binaries

- source/DEINDUGens/sc/HelpSource/Classes/JPverbRaw.schelp
The class definition and help file argument order did not match. This fixes that, and squashes some warnings that occur when loading the help document.
> Reorder JPverbRaw arguments in help file.

- _data/releases.yml
- package/create_package.sh
Here are two unrelated updates:
- update gpg command to match the one in the main SuperCollider repo (I used it to create signature for 3.13.0-rc1 source package)
- add the latest tag so that it is linked on the sc3-plugins website
> 3.13.0-rc1 updates

- .github/workflows/CI.yml
As mentioned in #379 
Interestingly enough, the macOS artifact zip does not have `._` files in it?
> Bump to macos 14 in CI

- .github/workflows/CI.yml
Inspired by the recent macOS runner update, I thought it would be nice to update other runners to newer versions. 
These changes might be preceding the changes to SC's CI, but I'm pretty sure that by the time we are ready for the 3.14 release, we'll be using at least these versions of the deployment tools.
> GHA: update runners to newer versions

- source/BhobUGens/sc/HelpSource/Classes/PV_Morph.schelp
- source/BhobUGens/sc/HelpSource/Classes/PV_XFade.schelp
Even though we're "not maintaining" sc3-plugins... every time I need to use PV_Morph or PV_XFade, I always have to look it up in the C++ source code to find out which one it is Cartesian and which one is polar. This really should be in the help, but isn't: "Morphs between two fft buffers" and "Interpolates bins between two fft buffers" leaves too much to the imagination.
> Help: Explain PV_Morph = polar interp and PV_XFade = Cartesian interp

- .github/workflows/jekyll.yml
Ubuntu 20.04 images are being removed, let's upgrade...
FYI Jekyll build is set up so that changes to the website can be checked against the build system.
> CI: Update jekyll.yml to Ubuntu 24.04

- .github/workflows/CI.yml
This updates the workflow to remove the warning ```The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. ```
> [ci] update filename setting step's output format

- .github/workflows/CI.yml
- CMakeLists.txt
- cmake_modules/launch-c.in
- cmake_modules/launch-cxx.in
This PR copies ccache implementation from Supercollider, adding logic to CMakeLists.txt and fixing/adding entries in the CI.
Previously ccache was partially enabled for Linux only, but it didn't work lately, probably due to updated ccache location and possibly updated cmake logic.
Tested here:  https://github.com/dyfer/sc3-plugins/actions/runs/17883065855 (total build time: 2'50"; without ccache it's about 8')
With this repo being rarely updated, the cache is prone to expire, but in the rare instances where there are multiple pushes in shorter succession, tgus improves build times dramatically.
> build: fix/add ccache support
